### ISSUE TITLE
How to specify screen resolution?

### ISSUE THREAD

**Issue by avilano** [CircleCI-Public/cimg-node#178]
I can't find a way to change the screen resolution for the ubuntu image in order to run browser tests.

**Comment by felicianotech** [comment]
This depends on the tools you are using. Different tools have different ways to go about things. Since this is a server image, there's no real screen or monitor but you can change the virtualized window size. For example, if you were using Selenium (pre-installed) and Firefox, this Doc shows the setting you'd want to change: https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/firefox_exports_Options.html#windowSize

**Comment by avilano** [comment]
Thank you, I'm using Testcafe in combination with the cimg-node, google chorme and browser-tools. I am getting this warning when tests finish.

```
Warnings (1):
 --
  Was unable to maximize the window due to an error.

  The
  /home/circleci/bold/qa/node_modules/testcafe-browser-tools/bin/linux/glibc-64/maximize
  process failed with the null exit code.
```

Here is the job config:
```
<job-name>:
    working_directory: <some-path>
    docker:
      - image: cimg/node:lts-browsers
    resource_class: medium+
    steps:
      - checkout:
          path: <some-path>
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/install-packages
      - run:
```
