### ISSUE TITLE
Yarn 3 has issues as a result of build time variables NODE_VER and YARN_VER

### ISSUE THREAD

**Issue by chiqomar** [CircleCI-Public/cimg-node#247]
We recently had an issue with building our project in production, getting this error early on in the build:
```bash
#!/bin/bash -eo pipefail
yarn install --immutable
Usage Error: Unrecognized or legacy configuration settings found: ver - run "yarn config -v" to see the list of settings supported in Yarn (in <environment>)

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]

Exited with code exit status 1
```

the accompanying config code is the following:
```yaml
jobs:
  build:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            # unset Docker build time variables, yarn 3 don't like that
            unset NODE_VER
            unset YARN_VER
            yarn install --immutable
```

After some difficulty, we tracked the issue down to `NODE_VER`  and `YARN_VER` variables, likely build time variables for the container. Unsetting these values allowed us to run yarn properly.

I believe we need these two variable names (`NODE_VER`  and `YARN_VER`) to be changed in order to avoid this issue in the future.
