### ISSUE TITLE
Using node 10.18.0 git command display warnings Permission denied

### ISSUE THREAD

**Issue by clakech** [CircleCI-Public/cimg-node#82]
Hello,

I switch to this new cimg/node:10.18.0 and when I run the command git add test.txt I get warnings:

```
warning: unable to access '/home/circleci/.config/git/ignore': Permission denied
warning: unable to access '/home/circleci/.config/git/attributes': Permission denied
```

I have open a support ticket for this but the answer is to use "a Machine User or a Deployment Key" and I don't get why and how this could solve those warnings.

Here is the full config to reproduce warnings:
```
  sample:
    docker:
      - image: cimg/node:10.18.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: touch test.txt && git add test.txt
```

I didn't get any warnings when I use circleci/node:10.18.0
